name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-dev.68.0 <3.15.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - images/ball1.png
    - images/ball2.png
    - images/ball3.png
    - images/ball4.png
    - images/ball5.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Sanz
      fonts:
        - asset: fonts/SourceSans3-VariableFont_wght.ttf

